"""State management for the info_and_recommendation graph.

This module defines the state structures used in the info_and_recommendation graph. It includes the 
definition for RecommendationAgentState, which is an extended version of the InputState.
"""

import pandas as pd
from dataclasses import dataclass, field
from typing import Annotated, Literal, TypedDict, Optional, List, Dict, Tuple

from app.shared.state import InputState


# This is the primary state of your agent, where you can store any information.
@dataclass(kw_only=True)
class RecommendationAgentState(InputState):
    """State of the retrieval graph / agent."""
    # Evaluation agent's user preferences
    user_preferences: List[str] = field(default_factory=list)
    """The list of user preferences provided by the evaluation agent."""
    # Evaluation agent's user response satisfaction report
    report : Tuple[str, str] = field(default_factory=tuple)  # Tuple["last_active_agent", "report"]
    """The report about the user's response satisfaction generated by the evaluation agent for the last active agent."""

    # Recommended movies
    recommended_movies_df: pd.DataFrame = field(default_factory=pd.DataFrame)
    """The DataFrame containing the recommended movies."""
